language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: msanchez@cognitivescale.com
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: arqzeb/UexBtk/QYGA0g20JG2ltUsqi9B2ZmlngCwoGCk94R83R2da7BDEUdhhQcpgFCjAz0O2BJXqOeoR4rvQDSuWa90Vm+u8tFb14BEo+vbOs+4IT1/ymuQEzwMJ3HwuuzymiTmf7TRgDw+pN/FcT2clhxqRyiX/Af5dK2xlSVD6ekQuv2ylOP+cf+Ux3JGF7yYauGVCu+aI1FiO4iF2i1ODuLbDEDUPR1MWoeF7oJT9q5dzYbhvJUkKpazGd4S5DtaN2R/nPbl9p+HtlK/P+I27FSP35cVbZYsu39Gd66lYgNYzzdQvVpyCJxMh5T+TeZezl80IqmJ7+2tpuedufnBJGC58Na4EQrJEZ9XtuMyV4R6K+0FaNkmg50a2pfUUwu6zFcuuhWPozNubRm0GECrQ98Mqqt3W2dq+7wy9Y4IiUeVt/jte4cm6HkVHDyfHbTjvwlrTCYmFw0geJS03/OTxzqURZheZ4g5E/gME4dpBuWRg3Y2M8/rYQe5EwSoU4VRKxHW0K6egwXS96Gw4vdD81ONHnlCWZOdYFV1USvomApYIcBWtKe/O5e6xguC6zSRPWeGVfEHqpgRtWft1e4ZROT/Eu+vEDBdz0HvmUSsa5oob2iZKFiE6Xrd+cwDwpbEJIKSrRUyzo0eJQ+vLZENkfmPjNiTaKpHQAB8MY=
