language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: msanchez@cognitivescale.com
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: uOI1CLln65yxZRjLYJARWM2JdygL9ytBgUNN7eBFVXzvHojFDvJUcI9fXWxRYljaSwh0t8S3Xl7T5GKJDQf3Oe1szbHLmFbin2dNOls4nlYvgrKzJBi/bwGoE59VqVK+mvYMqgbfKS50B/DxivxbbIQGxMOyyZDMJ0+wj63/6O8roAkhPuiMz59xhZT4KjnD2N8vcbEDtBJ0GDiVBKELPNdA7fDsHfUKAGVxlk2iGHIs/jQYOS8C9ErSJ3+8hKcF8dy3lLGd8obKb6I6yL9ZKLU8sBIKum6PAcoLN8K33eF+c5142nqcn/l7op2m2e3x1ia7DnxZaQhxbOLWiwvavwJ9bn+bF/jV9r4qiJSmn1gcSNbdzYBn4jIrtjEBCPDPT3U1ZNEYyH59N4wK+fPJ+YmroMXFHyo0qZBg93k+/hZm3AJo8MCg4gUyv2PYlJOoWj3R9qAlY37C9ugeLIpPTDAWUP1VWa5a6sNBNn9k7XhMR0KZVjJtUYT9GITN8O7+Vznj4XKpigtIVOzrEzVrjnQGFFeylOW+Hxy3lEdudFGMq8msdcZdKhxiIArkRqJMBz9iLda/gq73978uplkVIFxpIfnXO/5i1fjw8uRdNN612QlyO4UgE0AnEecrGYsredqEZoLMOYzhwZpL1ngAnynKfddeJXp+JSrvV3Ya/3E=
#deploy:
#  provider: npm
#  email: msanchez@cognitivescale.com
#  skip_cleanup: true
#  on:
#    branch: staging
#  api_key:
#    secure: uOI1CLln65yxZRjLYJARWM2JdygL9ytBgUNN7eBFVXzvHojFDvJUcI9fXWxRYljaSwh0t8S3Xl7T5GKJDQf3Oe1szbHLmFbin2dNOls4nlYvgrKzJBi/bwGoE59VqVK+mvYMqgbfKS50B/DxivxbbIQGxMOyyZDMJ0+wj63/6O8roAkhPuiMz59xhZT4KjnD2N8vcbEDtBJ0GDiVBKELPNdA7fDsHfUKAGVxlk2iGHIs/jQYOS8C9ErSJ3+8hKcF8dy3lLGd8obKb6I6yL9ZKLU8sBIKum6PAcoLN8K33eF+c5142nqcn/l7op2m2e3x1ia7DnxZaQhxbOLWiwvavwJ9bn+bF/jV9r4qiJSmn1gcSNbdzYBn4jIrtjEBCPDPT3U1ZNEYyH59N4wK+fPJ+YmroMXFHyo0qZBg93k+/hZm3AJo8MCg4gUyv2PYlJOoWj3R9qAlY37C9ugeLIpPTDAWUP1VWa5a6sNBNn9k7XhMR0KZVjJtUYT9GITN8O7+Vznj4XKpigtIVOzrEzVrjnQGFFeylOW+Hxy3lEdudFGMq8msdcZdKhxiIArkRqJMBz9iLda/gq73978uplkVIFxpIfnXO/5i1fjw8uRdNN612QlyO4UgE0AnEecrGYsredqEZoLMOYzhwZpL1ngAnynKfddeJXp+JSrvV3Ya/3E=
#  tag:
#    staging
